name: "TYPO3 v14"

on:
  pull_request:
  workflow_dispatch:

jobs:

  code-quality:
    name: "code quality"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2" ]
        typo3: [ "14" ]
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Prepare dependencies for TYPO3 v${{ matrix.typo3 }}"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s composerUpdate"

      - name: "CGL"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s cgl -n"

      - name: "Static code analyzer"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s phpstan"

      - name: "Ensure UTF-8 files do not contain BOM"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s checkBom"

      - name: "Find duplicate exception codes"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s checkExceptionCodes"

      - name: "Ensure test methods do not start with \"test\""
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s checkTestMethodsPrefix"

  linting:
    name: "linting"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2", "8.3", "8.4", "8.5" ]
        typo3: [ "14" ]
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Prepare dependencies for TYPO3 v${{ matrix.typo3 }}"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s composerUpdate"

      - name: "Run PHP lint"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s lintPhp"

  unit:
    name: "unit"
    runs-on: ubuntu-latest
    needs: [ "code-quality", "linting" ]
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2", "8.5" ]
        typo3: [ "14" ]
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Prepare dependencies for TYPO3 v${{ matrix.typo3 }}"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s composerUpdate"

      - name: "Execute unit tests"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s unit"

  functional:
    name: "functional"
    runs-on: ubuntu-22.04
    needs: [ "code-quality", "linting", "unit" ]
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.2", "8.5" ]
        typo3: [ "14" ]
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Prepare dependencies for TYPO3 v${{ matrix.typo3 }}"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -s composerUpdate"

      - name: "functional with SQLite"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -d sqlite -s functional"

      - name: "functional with MySQL 8.0"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -d mysql -i 8.0 -s functional"

      - name: "functional with MariaDB 10.4"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -d mariadb -i 10.4 -s functional"

      - name: "functional with MariaDB 10.6"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -d mariadb -i 10.6 -s functional"

      - name: "functional with Postgres 10"
        run: "Build/Scripts/runTests.sh -t ${{ matrix.typo3 }} -p ${{ matrix.php-version }} -d postgres -i 10 -s functional"
